name: Check event types
on:
  pull_request:
    types:
      - opened
      - edited
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"



