name: Test Skip ci
on:
  push:
    branches:
      - master

jobs:
  test_skip_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"



